"""Searching for conflict-free timetables and ranking them."""

from .constraints import (
    CampusIs,
    CandidateFilter,
    EarliestStart,
    ExcludeSection,
    ExcludeTeacher,
    FreeDay,
    LatestEnd,
    MaxDays,
    MaxGapMinutes,
    MaxIdleMinutes,
    MaxOnsiteDays,
    MinCredits,
    ModalityIs,
    RequireSection,
    SectionFilter,
    split_filters,
)
from .scoring import (
    BALANCED,
    SCORERS,
    Composite,
    MostCredits,
    MostElectives,
    Scorer,
    ranked,
    top_n,
)
from .solver import (
    ElectiveTally,
    SolveStats,
    Unsatisfiable,
    count_candidates,
    elective_report,
    find_blocking_pair,
    iter_candidates,
    prepare,
)

__all__ = [
    "BALANCED",
    "SCORERS",
    "CampusIs",
    "CandidateFilter",
    "Composite",
    "ElectiveTally",
    "EarliestStart",
    "ExcludeSection",
    "ExcludeTeacher",
    "FreeDay",
    "LatestEnd",
    "MaxDays",
    "MaxGapMinutes",
    "MaxIdleMinutes",
    "MaxOnsiteDays",
    "MinCredits",
    "ModalityIs",
    "MostCredits",
    "MostElectives",
    "RequireSection",
    "Scorer",
    "SectionFilter",
    "SolveStats",
    "Unsatisfiable",
    "count_candidates",
    "elective_report",
    "find_blocking_pair",
    "iter_candidates",
    "prepare",
    "ranked",
    "split_filters",
    "top_n",
]
